libKernels := \
__error \
__inet_ntop \
__inet_pton \
__pthread_cleanup_pop_imp \
__pthread_cleanup_push_imp \
__stack_chk_fail \
__stack_chk_fail_local \
__stack_chk_guard \
_exit \
accept \
access \
aio_cancel \
aio_error \
aio_fsync \
aio_read \
aio_return \
aio_suspend \
aio_waitcomplete \
aio_write \
amd64_set_fsbase \
bind \
chdir \
chflags \
chmod \
chown \
chroot \
clock_getres \
clock_gettime \
clock_settime \
close \
connect \
cpuset \
cpuset_getaffinity \
cpuset_getid \
cpuset_setaffinity \
cpuset_setid \
creat \
dlclose \
dlerror \
dlopen \
dlsym \
dup \
dup2 \
execv \
execve \
execvp \
fchdir \
fchflags \
fchmod \
fchmodat \
fchown \
fchownat \
fcntl \
flock \
fork \
fpathconf \
fstat \
fstatat \
fsync \
ftruncate \
futimes \
futimesat \
getcontext \
getdents \
getdirentries \
getdtablesize \
getegid \
geteuid \
getgid \
getgroups \
getitimer \
getlogin \
getlogin_r \
getpagesize \
getpeername \
getpid \
getppid \
getpriority \
getrlimit \
getrusage \
getsid \
getsockname \
getsockopt \
gettimeofday \
getuid \
htonl \
htons \
inet_ntop \
inet_pton \
ioctl \
issetugid \
kevent \
kill \
kldfind \
kldfirstmod \
kldload \
kldnext \
kldstat \
kldsym \
kldunload \
kqueue \
ksem_close \
ksem_destroy \
ksem_getvalue \
ksem_init \
ksem_open \
ksem_post \
ksem_timedwait \
ksem_trywait \
ksem_unlink \
ksem_wait \
lchflags \
lchmod \
lchown \
link \
linkat \
listen \
lseek \
lstat \
lutimes \
madvise \
mincore \
mkdir \
mkdirat \
mlock \
mlockall \
mmap \
mprotect \
msync \
munlock \
munlockall \
munmap \
nanosleep \
ntohl \
ntohs \
open \
openat \
pathconf \
pause \
pipe \
poll \
pread \
preadv \
profil \
pselect \
pthread_atfork \
pthread_attr_destroy \
pthread_attr_getdetachstate \
pthread_attr_getguardsize \
pthread_attr_getinheritsched \
pthread_attr_getschedparam \
pthread_attr_getschedpolicy \
pthread_attr_getscope \
pthread_attr_getstack \
pthread_attr_getstackaddr \
pthread_attr_getstacksize \
pthread_attr_init \
pthread_attr_setdetachstate \
pthread_attr_setguardsize \
pthread_attr_setinheritsched \
pthread_attr_setschedparam \
pthread_attr_setschedpolicy \
pthread_attr_setscope \
pthread_attr_setstack \
pthread_attr_setstackaddr \
pthread_attr_setstacksize \
pthread_barrier_destroy \
pthread_barrier_init \
pthread_barrier_wait \
pthread_barrierattr_destroy \
pthread_barrierattr_getpshared \
pthread_barrierattr_init \
pthread_barrierattr_setpshared \
pthread_cancel \
pthread_cond_broadcast \
pthread_cond_destroy \
pthread_cond_init \
pthread_cond_signal \
pthread_cond_timedwait \
pthread_cond_wait \
pthread_condattr_destroy \
pthread_condattr_getclock \
pthread_condattr_getpshared \
pthread_condattr_init \
pthread_condattr_setclock \
pthread_condattr_setpshared \
pthread_create \
pthread_detach \
pthread_equal \
pthread_exit \
pthread_getconcurrency \
pthread_getcpuclockid \
pthread_getprio \
pthread_getschedparam \
pthread_getspecific \
pthread_join \
pthread_key_create \
pthread_key_delete \
pthread_kill \
pthread_mutex_destroy \
pthread_mutex_getprioceiling \
pthread_mutex_init \
pthread_mutex_lock \
pthread_mutex_setprioceiling \
pthread_mutex_timedlock \
pthread_mutex_trylock \
pthread_mutex_unlock \
pthread_mutexattr_destroy \
pthread_mutexattr_getprioceiling \
pthread_mutexattr_getprotocol \
pthread_mutexattr_getpshared \
pthread_mutexattr_gettype \
pthread_mutexattr_init \
pthread_mutexattr_setprioceiling \
pthread_mutexattr_setprotocol \
pthread_mutexattr_setpshared \
pthread_mutexattr_settype \
pthread_once \
pthread_rwlock_destroy \
pthread_rwlock_init \
pthread_rwlock_rdlock \
pthread_rwlock_timedrdlock \
pthread_rwlock_timedwrlock \
pthread_rwlock_tryrdlock \
pthread_rwlock_trywrlock \
pthread_rwlock_unlock \
pthread_rwlock_wrlock \
pthread_rwlockattr_destroy \
pthread_rwlockattr_getpshared \
pthread_rwlockattr_init \
pthread_rwlockattr_setpshared \
pthread_self \
pthread_setcancelstate \
pthread_setcanceltype \
pthread_setconcurrency \
pthread_setprio \
pthread_setschedparam \
pthread_setspecific \
pthread_sigmask \
pthread_spin_destroy \
pthread_spin_init \
pthread_spin_lock \
pthread_spin_trylock \
pthread_spin_unlock \
pthread_testcancel \
pthread_yield \
ptrace \
pwrite \
pwritev \
raise \
read \
readlink \
readv \
reboot \
recv \
recvfrom \
recvmsg \
rename \
renameat \
revoke \
rfork_thread \
rmdir \
rtprio_thread \
sceKernelAddReadEvent \
sceKernelAddUserEvent \
sceKernelAllocateDirectMemory \
sceKernelCreateEqueue \
sceKernelDeleteEqueue \
sceKernelWaitEqueue \
sceKernelDlsym \
sceKernelGetDirectMemorySize \
sceKernelGetCurrentCpu \
sceKernelGetModuleInfo \
sceKernelGetModuleList \
sceKernelGetProcessTime \
sceKernelGettimeofday \
sceKernelJitCreateAliasOfSharedMemory \
sceKernelJitCreateSharedMemory \
sceKernelJitMapSharedMemory \
sceKernelLoadStartModule \
sceKernelMapDirectMemory \
sceKernelSleep \
sceKernelStopUnloadModule \
sceKernelUsleep \
scePthreadCancel \
scePthreadCreate \
scePthreadDetach \
scePthreadExit \
scePthreadJoin \
scePthreadMutexDestroy \
scePthreadMutexInit \
scePthreadMutexLock \
scePthreadMutexTimedlock \
scePthreadMutexTrylock \
scePthreadMutexUnlock \
scePthreadSelf \
scePthreadYield \
sched_get_priority_max \
sched_get_priority_min \
sched_getparam \
sched_getscheduler \
sched_rr_get_interval \
sched_setparam \
sched_setscheduler \
sched_yield \
select \
sem_close \
sem_destroy \
sem_getvalue \
sem_init \
sem_open \
sem_post \
sem_timedwait \
sem_trywait \
sem_unlink \
sem_wait \
send \
sendfile \
sendmsg \
sendto \
setcontext \
setegid \
seteuid \
setgroups \
setitimer \
setlogin \
setpgid \
setpriority \
setregid \
setreuid \
setrlimit \
setsid \
setsockopt \
settimeofday \
setuid \
shm_open \
shm_unlink \
shutdown \
sigaction \
sigaddset \
sigaltstack \
sigdelset \
sigemptyset \
sigfillset \
sigismember \
siglongjmp \
signal \
sigpending \
sigprocmask \
sigqueue \
sigreturn \
sigsetjmp \
sigsuspend \
sigtimedwait \
sigwait \
sigwaitinfo \
sleep \
socket \
socketpair \
stat \
swapcontext \
swapon \
symlink \
symlinkat \
sync \
sysarch \
syscall \
sysconf \
sysctl \
sysctlbyname \
sysctlnametomib \
system \
tcdrain \
tcflow \
tcflush \
tcgetattr \
tcgetpgrp \
tcgetsid \
tcsendbreak \
tcsetattr \
tcsetpgrp \
tcsetsid \
truncate \
umask \
unlink \
unlinkat \
usleep \
utimes \
vfork \
wait \
wait3 \
wait4 \
waitpid \
write \
writev
