###################################

Ps4Sdk ?= $(CURDIR)/..

target := ps4_stub_lib
BuildPath := $(Ps4Sdk)/build
OutPath := $(Ps4Sdk)/lib

###################################

include $(Ps4Sdk)/make/ps4sdk.mk

include $(CURDIR)/stub.mk

###################################
